### ISSUE TITLE
Failed to read 'glew\include\GL\glew.h'

### ISSUE THREAD

**Issue by leon196** [KoltesDigital/shiba#2]
The system console throw this error when enabled Rendered shading in Shiba

**Comment by leon196** [comment]
Shiba needs to know the paths of glew with a config.yml.
This files needs to be inside C:\Users\\[UserName]\\.shiba\config.yml
It looks like this:
```yml
paths:
    glew: "D:\\Tools\\glew-2.1.0"
    python2: "C:\\Python27\\python.exe"
```
